# Generated by Django 5.0.2 on 2025-01-15 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_tinymce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CKEditorContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CKEditor Content",
                "verbose_name_plural": "CKEditor Contents",
            },
        ),
    ]
