# Generated by Django 5.0.2 on 2025-01-11 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Select to display this post in the featured section",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_on"], name="blog_post_created_898b61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-created_on"], name="blog_post_status_210572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["featured", "-created_on"], name="blog_post_feature_c960eb_idx"
            ),
        ),
    ]
