# Generated by Django 5.0.2 on 2025-01-12 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="fas fa-book", help_text="FontAwesome icon class", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="estimated_time",
            field=models.CharField(
                blank=True,
                default="1 hour",
                help_text="e.g., '2 hours', '30 minutes'",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="prerequisites",
            field=models.ManyToManyField(blank=True, to="learning.tutorial"),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="summary",
            field=models.TextField(
                blank=True, help_text="A brief summary of the tutorial", null=True
            ),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="tutorials/thumbnails/"
            ),
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("progress_percent", models.IntegerField(default=0)),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.tutorial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tutorial")},
            },
        ),
    ]
