# Generated by Django 5.0.2 on 2025-01-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_tutorial_author_tutorial_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="icon",
            field=models.CharField(
                default="fas fa-book",
                help_text="FontAwesome icon class (e.g., 'fas fa-robot')",
                max_length=50,
            ),
        ),
    ]
