# Generated by Django 5.0.2 on 2025-01-15 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fas fa-robot", "Robot"),
                            ("fas fa-brain", "Brain"),
                            ("fas fa-microchip", "Microchip"),
                            ("fas fa-network-wired", "Neural Network"),
                            ("fas fa-project-diagram", "Neural Connections"),
                            ("fas fa-sitemap", "Deep Learning"),
                            ("fas fa-code", "Code"),
                            ("fas fa-laptop-code", "Laptop with Code"),
                            ("fas fa-terminal", "Terminal"),
                            ("fas fa-bug", "Debug"),
                            ("fas fa-file-code", "Code File"),
                            ("fas fa-keyboard", "Keyboard"),
                            ("fas fa-database", "Database"),
                            ("fas fa-server", "Server"),
                            ("fas fa-chart-line", "Analytics Graph"),
                            ("fas fa-chart-bar", "Bar Chart"),
                            ("fas fa-chart-pie", "Pie Chart"),
                            ("fas fa-table", "Data Table"),
                            ("fas fa-cloud", "Cloud"),
                            ("fas fa-cloud-upload-alt", "Cloud Upload"),
                            ("fas fa-cloud-download-alt", "Cloud Download"),
                            ("fas fa-server", "Server"),
                            ("fas fa-hdd", "Storage"),
                            ("fas fa-memory", "Memory"),
                            ("fas fa-shield-alt", "Security Shield"),
                            ("fas fa-lock", "Lock"),
                            ("fas fa-key", "Key"),
                            ("fas fa-user-shield", "User Security"),
                            ("fas fa-fingerprint", "Biometric"),
                            ("fas fa-tools", "Tools"),
                            ("fas fa-cogs", "Settings Gears"),
                            ("fas fa-wrench", "Wrench"),
                            ("fas fa-sliders-h", "Sliders"),
                            ("fas fa-toolbox", "Toolbox"),
                            ("fas fa-graduation-cap", "Education"),
                            ("fas fa-book", "Book"),
                            ("fas fa-chalkboard-teacher", "Teaching"),
                            ("fas fa-user-graduate", "Graduate"),
                            ("fas fa-pencil-alt", "Writing"),
                            ("fas fa-microphone", "Voice/Audio"),
                            ("fas fa-camera", "Computer Vision"),
                            ("fas fa-language", "NLP"),
                            ("fas fa-comments", "Chatbot"),
                            ("fas fa-vr-cardboard", "Virtual Reality"),
                            ("fas fa-gamepad", "Gaming AI"),
                        ],
                        default="fas fa-flask",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "demo categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="A brief summary of the demo", null=True
                    ),
                ),
                ("content", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="demos/thumbnails/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("fas fa-robot", "Robot"),
                            ("fas fa-brain", "Brain"),
                            ("fas fa-microchip", "Microchip"),
                            ("fas fa-network-wired", "Neural Network"),
                            ("fas fa-project-diagram", "Neural Connections"),
                            ("fas fa-sitemap", "Deep Learning"),
                            ("fas fa-code", "Code"),
                            ("fas fa-laptop-code", "Laptop with Code"),
                            ("fas fa-terminal", "Terminal"),
                            ("fas fa-bug", "Debug"),
                            ("fas fa-file-code", "Code File"),
                            ("fas fa-keyboard", "Keyboard"),
                            ("fas fa-database", "Database"),
                            ("fas fa-server", "Server"),
                            ("fas fa-chart-line", "Analytics Graph"),
                            ("fas fa-chart-bar", "Bar Chart"),
                            ("fas fa-chart-pie", "Pie Chart"),
                            ("fas fa-table", "Data Table"),
                            ("fas fa-cloud", "Cloud"),
                            ("fas fa-cloud-upload-alt", "Cloud Upload"),
                            ("fas fa-cloud-download-alt", "Cloud Download"),
                            ("fas fa-server", "Server"),
                            ("fas fa-hdd", "Storage"),
                            ("fas fa-memory", "Memory"),
                            ("fas fa-shield-alt", "Security Shield"),
                            ("fas fa-lock", "Lock"),
                            ("fas fa-key", "Key"),
                            ("fas fa-user-shield", "User Security"),
                            ("fas fa-fingerprint", "Biometric"),
                            ("fas fa-tools", "Tools"),
                            ("fas fa-cogs", "Settings Gears"),
                            ("fas fa-wrench", "Wrench"),
                            ("fas fa-sliders-h", "Sliders"),
                            ("fas fa-toolbox", "Toolbox"),
                            ("fas fa-graduation-cap", "Education"),
                            ("fas fa-book", "Book"),
                            ("fas fa-chalkboard-teacher", "Teaching"),
                            ("fas fa-user-graduate", "Graduate"),
                            ("fas fa-pencil-alt", "Writing"),
                            ("fas fa-microphone", "Voice/Audio"),
                            ("fas fa-camera", "Computer Vision"),
                            ("fas fa-language", "NLP"),
                            ("fas fa-comments", "Chatbot"),
                            ("fas fa-vr-cardboard", "Virtual Reality"),
                            ("fas fa-gamepad", "Gaming AI"),
                        ],
                        default="fas fa-flask",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demos.democategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
