# Generated by Django 5.0.2 on 2025-01-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for the demo",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="demo",
            name="use_cases",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("technical", "Technical"),
                    ("educational", "Educational"),
                ],
                default="technical",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="democategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="demos.democategory",
            ),
        ),
    ]
