# Generated by Django 5.0.2 on 2025-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0002_demo_tags_demo_use_cases_democategory_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="estimated_time",
            field=models.CharField(
                blank=True,
                help_text="Estimated time to complete the demo",
                max_length=20,
                null=True,
            ),
        ),
    ]
