# Generated by Django 5.0.2 on 2025-01-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0003_demo_estimated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="democategory",
            name="sub_parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="demos.democategory",
            ),
        ),
        migrations.AlterField(
            model_name="democategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="demos.democategory",
            ),
        ),
    ]
