# Generated by Django 5.0.2 on 2025-01-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0006_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        help_text="CharField for text input", max_length=100
                    ),
                ),
                (
                    "choice_field",
                    models.CharField(
                        choices=[("option1", "Option 1"), ("option2", "Option 2")],
                        help_text="ChoiceField for selecting an option",
                        max_length=50,
                    ),
                ),
                ("date_field", models.DateField(help_text="DateField for date input")),
                (
                    "datetime_field",
                    models.DateTimeField(
                        help_text="DateTimeField for date and time input"
                    ),
                ),
                (
                    "decimal_field",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="DecimalField for decimal numbers",
                        max_digits=5,
                    ),
                ),
                (
                    "email_field",
                    models.EmailField(
                        help_text="EmailField for email input", max_length=254
                    ),
                ),
                (
                    "float_field",
                    models.FloatField(
                        help_text="FloatField for floating point numbers"
                    ),
                ),
                (
                    "integer_field",
                    models.IntegerField(help_text="IntegerField for integer numbers"),
                ),
                ("slug_field", models.SlugField(help_text="SlugField for URL slugs")),
                (
                    "text_field",
                    models.TextField(help_text="TextField for large text input"),
                ),
                ("url_field", models.URLField(help_text="URLField for URL input")),
            ],
        ),
    ]
