# Generated by Django 5.0.2 on 2025-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0007_sampleformmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampleformmodel",
            name="big_integer_field",
            field=models.BigIntegerField(
                blank=True, help_text="BigIntegerField for large integers", null=True
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="boolean_field",
            field=models.BooleanField(
                default=False, help_text="BooleanField for true/false values"
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="duration_field",
            field=models.DurationField(
                blank=True, help_text="DurationField for time duration", null=True
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="file_field",
            field=models.FileField(
                blank=True,
                help_text="FileField for file uploads",
                null=True,
                upload_to="uploads/",
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="generic_ip_address_field",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="GenericIPAddressField for IPv4/IPv6 addresses",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="image_field",
            field=models.ImageField(
                blank=True,
                help_text="ImageField for image uploads",
                null=True,
                upload_to="images/",
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="null_boolean_field",
            field=models.BooleanField(
                blank=True,
                help_text="BooleanField for true/false/null values",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="positive_integer_field",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="PositiveIntegerField for positive integers",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="positive_small_integer_field",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="PositiveSmallIntegerField for small positive integers",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="small_integer_field",
            field=models.SmallIntegerField(
                blank=True, help_text="SmallIntegerField for small integers", null=True
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="time_field",
            field=models.TimeField(
                blank=True, help_text="TimeField for time input", null=True
            ),
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="uuid_field",
            field=models.UUIDField(
                blank=True,
                help_text="UUIDField for universally unique identifiers",
                null=True,
            ),
        ),
    ]
