# Generated by Django 5.0.2 on 2025-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0008_sampleformmodel_big_integer_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampleformmodel",
            name="multi_line_text_field",
            field=models.TextField(
                blank=True, help_text="Multi-line text input", null=True
            ),
        ),
    ]
