# Generated by Django 5.0.2 on 2025-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0009_sampleformmodel_multi_line_text_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="sampleformmodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="Select tags for this item", to="demos.tag"
            ),
        ),
    ]
