# Generated by Django 5.0.2 on 2025-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0010_tag_sampleformmodel_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ["name"], "verbose_name_plural": "subcategories"},
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
