# Generated by Django 5.0.2 on 2025-01-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0011_alter_subcategory_options_subcategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demos",
                to="demos.subcategory",
            ),
        ),
    ]
