# Generated by Django 5.0.2 on 2025-01-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0012_demo_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demo",
            name="subcategory",
        ),
    ]
