# Generated by Django 5.0.2 on 2025-01-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demos", "0013_remove_demo_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demos",
                to="demos.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="demo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demos",
                to="demos.democategory",
            ),
        ),
    ]
